import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {Dropdown, Form} from "react-bootstrap";


//components
import Navbar from "../components/Navbar";
import Button from "react-bootstrap/Button";

const Ride = () => {
    //Funktionen

    //HTML
    return (
        <div className="container">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <main className="container">
                <div className="input-position mt-5">
                    <div className="d-flex flex-column justify-content-center">
                            <div className="flex-row">
                                <a className="nav-link d-flex justify-content-end link-style mb-2" href="/add-shipping">
                                <img
                                    src='/Vector.svg'
                                    alt="SVG send"
                                    width="3%"
                                    height="3%"
                                    className="send-icon-style"
                                />Fahrten veröffentlichen
                                </a>
                            </div>


                        <Form>
                            <input
                                type="text"
                                className="form-control input-styles mb-3"
                                placeholder="Von"
                                id="firstName"
                            />
                            <input
                                type="text"
                                className="form-control input-styles mb-3"
                                placeholder="Nach"
                                id="firstName"
                            />
                            <Dropdown>
                                <Dropdown.Toggle
                                    className="input-style mb-3 dropdown-style">
                                    Ware
                                </Dropdown.Toggle>
                                <Dropdown.Menu>
                                    <Dropdown.Item href="#">
                                        Paket
                                    </Dropdown.Item>
                                    <Dropdown.Item href="#">
                                        Fahrrad
                                    </Dropdown.Item>
                                    <Dropdown.Item href="#">
                                        Möbel
                                    </Dropdown.Item>
                                </Dropdown.Menu>
                            </Dropdown>

                            <div className="input-position">
                                <input
                                    type="text"
                                    className="form-control input-styles space-right mb-3"
                                    placeholder="max. Maße"
                                    id="firstName"
                                />
                                <input
                                    type="text"
                                    className="form-control input-styles space-left mb-3"
                                    placeholder="max. Gewicht"
                                    id="firstName"
                                />
                            </div>
                            <div className="input-position">
                                <input
                                    type="text"
                                    className="form-control input-styles space-right mb-3"
                                    placeholder="Preis"
                                    id="firstName"
                                />
                                <input
                                    type="text"
                                    className="form-control input-styles space-left mb-3"
                                    placeholder="Datum"
                                    id="firstName"
                                />
                            </div>
                            <Dropdown>
                                <Dropdown.Toggle
                                    className="input-style mb-3 dropdown-style">
                                    Fahrzeug
                                </Dropdown.Toggle>
                                <Dropdown.Menu>
                                    <Dropdown.Item href="#">
                                        VW Polo
                                    </Dropdown.Item>
                                    <Dropdown.Item href="#">
                                        Audi A1
                                    </Dropdown.Item>
                                    <Dropdown.Item href="#">
                                        Mercedes C-Klasse
                                    </Dropdown.Item>
                                </Dropdown.Menu>
                            </Dropdown>
                        </Form>
                        <div className="d-flex justify-content-center">
                            <Button className="btn-style mt-4 mb-4">
                                veröffentlichen
                            </Button>
                        </div>
                    </div>
                    <div>
                        <img
                            src='/delivery.svg'
                            alt="SVG von Ware versenden"
                            width="90%"
                            height="90%"
                        />
                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
                </a>
            </footer>
        </div>
    );
};

export default Ride;
