import Head from "next/head";
import styles from "../styles/Home.module.css";

//components
import Navbar from "../components/Navbar";
import React, { useState } from "react";
import { Button, Row } from "react-bootstrap";
import { Container } from "react-bootstrap";
import { Col } from "react-bootstrap";
import { Breadcrumb } from "react-bootstrap";
import { Card } from "react-bootstrap";
import { Image } from "react-bootstrap";
import { Modal } from "react-bootstrap";


const PaymentProcess3Kontostand= () => {
	const [show, setShow] = useState(false);

	const handleClose = () => setShow(false);
	const handleShow = () => setShow(true);

	//Funktionen

	//HTML
	return (
		<div className="container">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar/>

			<main className="container">
				{/*algin div center */}
				<Container>

					<Row className={styles.head}>
						<Col> 				
							<Modal className={styles.modalPayment} show={show} onHide={handleClose}>
								<Modal.Header closeButton>
									<Modal.Title>Kontodaten</Modal.Title>
								</Modal.Header>
								<Modal.Body>
									<p>Inhaber: MyCargonaut GmbH</p>
									<p>IBAN: DE15 245084 1122 0013</p>
									<p>BLZ: 3154359</p>
									<p>Verwendungszweck: cargonautjanschmidt13</p>											
									
								</Modal.Body>
								<Modal.Footer>
									<p>Um dein Guthaben aufzuladen sende den gewünschten Betrag an die oben stehenden Kontodaten.</p>
								
								</Modal.Footer>
							</Modal>							
						</Col>
					</Row>

					<Row className={styles.head}>
						<Col md={{ span: 8, offset: 2 }}>
							<h1>Mein Kontostand</h1>
						</Col>
					</Row>

					<Row>
						<Col md={{ span: 8, offset: 2 }}>
						<Card border="secondary">							
							<Card.Body>

								<Row >
									<Col>
										<Card.Text className={styles.guthaben}>+05,00€</Card.Text>
									</Col>
								</Row>							

								<Row>
									<Col>
										<Image className={styles.imgPaymentTree} src="/invest.svg" alt="money img" width={230} height={250} />
									</Col>
								</Row>

								<Row className="justify-content-md-center">
									<Col md="auto">
										<Button className={styles.btn} type="submit"  onClick={handleShow}>Konto aufladen</Button>
									</Col>									
								</Row>															
								
							</Card.Body>
						</Card>						
						</Col>
					</Row>
				</Container>
	
			</main>

			<footer className={styles.footer}>
			
			</footer>
		</div>
	);
};

export default PaymentProcess3Kontostand;

