import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

//components
import Navbar from "../components/Navbar";

const Profil = () => {
	//Funktionen

	//HTML
	return (
		<div className="container">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className="container">
				{/*algin div center l*/}
				<div className="row justify-content-center m-3">
					<img
						className="rounded-circle  col-sm-auto"
						src="https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200"
						alt="Profilbild"
						width="400"
						height="400"
					/>
				</div>
				<h1 className={styles.title}>Hans Peter</h1>

				<div className={styles.grid}></div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Profil;
