import Head from "next/head";
import styles from "../styles/Home.module.css";

//components
import Navbar from "../components/Navbar";
import React from "react";
import { Button, Row } from "react-bootstrap";
import { Container } from "react-bootstrap";
import { Col } from "react-bootstrap";
import { Breadcrumb } from "react-bootstrap";
import { Card } from "react-bootstrap";
import { Image } from "react-bootstrap";
import { ProgressBar } from 'react-bootstrap';


const PaymentProcess3Kontostand= () => {

	return (
		<div className="container">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar/>

			<main className="container">
				{/*algin div center */}
				<Container>

					<Row className={styles.head}>
						<Col  md={{ span: 8, offset: 2 }}>
                        <Breadcrumb className={styles.head}>
							<Breadcrumb.Item active>Auswahl prüfen</Breadcrumb.Item>
								<Breadcrumb.Item active>Informationen eingeben</Breadcrumb.Item>
								<Breadcrumb.Item active>Kauf abschließen</Breadcrumb.Item>
								<Breadcrumb.Item active>Buchungsbestätigung</Breadcrumb.Item>
                                <Breadcrumb.Item active>Fahrt tracken</Breadcrumb.Item>
							</Breadcrumb>							
						</Col>
					</Row>

					<Row className={styles.head}>
						<Col md={{ span: 8, offset: 2 }}>
							<h1>Fahrt tracken</h1>
						</Col>
					</Row>					
                    <Row>
						<Col md={{ span: 8, offset: 2 }}>
                        <Image src="/map.png" alt="map img" width={825} height={250}/>
						</Col>
					</Row>
                    
                    <Row>
                        <Col md={{ span: 8, offset: 2 }}>
                            <Card border="secondary" className={styles.cardTracking}>
                                <Card.Body>
                                    <Row>
                                    <Col md={{ span: 10, offset: 1 }}>
                                        <ProgressBar>
                                            <ProgressBar variant="success" now={25} key={1} />                            
                                        </ProgressBar>
                                    </Col>
                                    </Row>
                                    <Row>
                                        <Col md={{ span: 2, offset:2 }}>
                                            <span>Buchung</span>
                                        </Col>
                                        <Col md={{ span: 2 }}>
                                            <span>Start</span>
                                        </Col>
                                        <Col md={{ span: 2 }}>
                                            <span>Ziel</span>
                                        </Col>
                                        <Col md={{ span: 2 }}>
                                            <span>Bestätigung</span>
                                        </Col>
                                    </Row>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>	

					<Row>
						<Col md={{ span: 4, offset: 2 }}>
						<Card border="secondary" className={styles.cardTracking}>							
							<Card.Body>
								<Row >
									<Col>
										<Card.Text>Lieferung:</Card.Text>
                                        <Card.Text>Monsera Pflanze</Card.Text>
									</Col>
								</Row>			
							</Card.Body>
						</Card>						
						</Col>

                        <Col md={{ span: 4}}>
						<Card border="secondary" className={styles.cardTracking}>							
							<Card.Body>								
                                <Row >
									<Col>
										<Card.Text>Dein Fahrer:</Card.Text>
                                        <Card.Text>Max Schneider</Card.Text>
									</Col>
								</Row>
							</Card.Body>
						</Card>						
						</Col>
					</Row>
				</Container>
	
			</main>

			<footer className={styles.footer}>
			
			</footer>
		</div>
	);
};

export default PaymentProcess3Kontostand;